name: Interline Hub Demo Java CICD

on:
  push:
    branches:
      - develop

  

jobs:  
  entrypoint:
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/entrypoint.yaml@develop
    with:
      recipe: java
      deploy: lambda

  #test:
  #  needs: [entrypoint]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/testJavaMaven.yaml@develop
  #  
  #build:
  #  needs: [entryPoint]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/buildJavaMaven.yaml@develop
  #
  #sonarScan:
  #  needs: [entryPoint, test, build]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/sonarCloudScan.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
  #
  #registry:
  #  needs: [entryPoint, sonarScan]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/registryS3.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
  #    branchName : ${{ needs.entrypoint.outputs.branchName }}
  #
  #deploy:
  #  needs: [entryPoint, registry]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/deployLambda.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
  #    branchName : ${{ needs.entrypoint.outputs.branchName }}
       
