name: Interline Hub Demo Java CICD

on:
  push:
    branches:
      - develop

jobs:  
  entrypoint:
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/entrypoint.yaml@develop
    secrets: inherit
    with:
      recipe: java
      provider: lambda
      
      