name: Java CICD

on:
  push:
    branches:
      - develop

jobs:
  entrypoint:
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/entrypoint.yaml@develop
  
  buildAndTest:
    needs: [entryPoint]
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/buildJavaMaven.yaml@develop
    
#
  #    #- name: sonarCloudQualityGate
  #    #  id: sonarqube-quality-gate-check
  #    #  uses: sonarsource/sonarqube-quality-gate-action@master
  #    #  # Force to fail step after specific time.
  #    #  timeout-minutes: 5
  #    #  env:
  #    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #    #  with:
  #    #    scanMetadataReportFile: src/.scannerwork/report-task.txt
  #          
  #    - name: registry 
  #      uses: hkusu/s3-upload-action@v2
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: 'eu-west-2'
  #        aws-bucket: 'aigcih-${{ needs.entrypoint.outputs.artifactId }}'
  #        file-path: './target/${{ needs.entrypoint.outputs.artifactId }}.jar'
  #        destination-dir: '/${{ needs.entrypoint.outputs.branchName }}/${{ needs.entrypoint.outputs.version }}'
  #
  #deployLambdaFunction:
  #  needs: [entryPoint, buildAndTest]
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: deployAWSLambda
  #    uses: appleboy/lambda-action@master
  #    with:
  #      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      aws_region: 'eu-west-2'
  #      function_name: AIGCIH_UpdateFunctionProcess_Development
  #      s3_bucket: 'aigcih-${{ needs.entrypoint.outputs.artifactId }}'
  #      s3_key: 'artifacts/${{ needs.entrypoint.outputs.branchName }}/${{ needs.entrypoint.outputs.version }}/${{ needs.entrypoint.outputs.artifactId }}.jar'
